In [30]:
import numpy as np
theta = np.pi/8
s = np.sin(theta)
c = np.cos(theta)
R = np.array(((c , -s),(s, c)))
v = np.array((1,1))

In [31]:
R

array([[ 0.92387953, -0.38268343],
       [ 0.38268343,  0.92387953]])

In [19]:
v

array([1, 1])

In [20]:
0.9848*2 -1*0.1736

1.796

In [23]:
R.dot(v.T)

array([1.11022302e-16, 1.41421356e+00])

In [25]:
R @ R.T

array([[1.00000000e+00, 1.01465364e-17],
       [1.01465364e-17, 1.00000000e+00]])

In [27]:
epsilon = np.array(((0,0.5),(0.5,0)))

In [32]:
R @ epsilon @ R.T

array([[-0.35355339,  0.35355339],
       [ 0.35355339,  0.35355339]])

array([[1.00000000e+00, 1.01465364e-17],
       [1.01465364e-17, 1.00000000e+00]])